"""Create users table for authentication

Revision ID: 117467b59ac9
Revises: 
Create Date: 2025-12-06 14:48:42.127328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '117467b59ac9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('type_source', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fiabilite', sa.Float(), nullable=True),
    sa.Column('derniere_maj', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_index(op.f('ix_data_sources_id'), 'data_sources', ['id'], unique=False)
    op.create_table('domaines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['domaines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domaines_id'), 'domaines', ['id'], unique=False)
    op.create_index(op.f('ix_domaines_nom'), 'domaines', ['nom'], unique=True)
    op.create_table('etablissements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=500), nullable=False),
    sa.Column('type_etablissement', sa.String(length=100), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('telephone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('site_web', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etablissements_id'), 'etablissements', ['id'], unique=False)
    op.create_index(op.f('ix_etablissements_nom'), 'etablissements', ['nom'], unique=False)
    op.create_index(op.f('ix_etablissements_region'), 'etablissements', ['region'], unique=False)
    op.create_index(op.f('ix_etablissements_ville'), 'etablissements', ['ville'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('niveau_etude', sa.String(length=100), nullable=True),
    sa.Column('domaine_interet', sa.String(length=255), nullable=True),
    sa.Column('region_preference', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_table('formations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intitule', sa.String(length=500), nullable=False),
    sa.Column('diplome', sa.String(length=255), nullable=True),
    sa.Column('niveau', sa.String(length=100), nullable=True),
    sa.Column('duree', sa.String(length=50), nullable=True),
    sa.Column('etablissement_id', sa.Integer(), nullable=False),
    sa.Column('conditions_admission', sa.Text(), nullable=True),
    sa.Column('objectifs', sa.Text(), nullable=True),
    sa.Column('debouches', sa.Text(), nullable=True),
    sa.Column('cout_inscription', sa.Float(), nullable=True),
    sa.Column('bourses_disponibles', sa.Boolean(), nullable=True),
    sa.Column('est_accredite', sa.Boolean(), nullable=True),
    sa.Column('organisme_accreditation', sa.String(length=255), nullable=True),
    sa.Column('data_source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formations_diplome'), 'formations', ['diplome'], unique=False)
    op.create_index(op.f('ix_formations_id'), 'formations', ['id'], unique=False)
    op.create_index(op.f('ix_formations_intitule'), 'formations', ['intitule'], unique=False)
    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('niveau_actuel', sa.String(length=100), nullable=True),
    sa.Column('serie_bac', sa.String(length=50), nullable=True),
    sa.Column('moyenne_generale', sa.Float(), nullable=True),
    sa.Column('matieres_fortes', sa.JSON(), nullable=True),
    sa.Column('matieres_faibles', sa.JSON(), nullable=True),
    sa.Column('domaines_interet', sa.JSON(), nullable=True),
    sa.Column('activites_extrascolaires', sa.JSON(), nullable=True),
    sa.Column('passions', sa.Text(), nullable=True),
    sa.Column('competences_techniques', sa.JSON(), nullable=True),
    sa.Column('competences_soft', sa.JSON(), nullable=True),
    sa.Column('langues', sa.JSON(), nullable=True),
    sa.Column('experiences', sa.JSON(), nullable=True),
    sa.Column('metiers_vises', sa.JSON(), nullable=True),
    sa.Column('secteur_activite', sa.String(length=255), nullable=True),
    sa.Column('niveau_etudes_vise', sa.String(length=100), nullable=True),
    sa.Column('projet_professionnel', sa.Text(), nullable=True),
    sa.Column('budget_max', sa.Float(), nullable=True),
    sa.Column('regions_acceptees', sa.JSON(), nullable=True),
    sa.Column('mobilite_internationale', sa.Boolean(), nullable=True),
    sa.Column('besoin_bourse', sa.Boolean(), nullable=True),
    sa.Column('contraintes_familiales', sa.Text(), nullable=True),
    sa.Column('type_etablissement_prefere', sa.String(length=100), nullable=True),
    sa.Column('taille_classe_preferee', sa.String(length=50), nullable=True),
    sa.Column('modalite_enseignement', sa.JSON(), nullable=True),
    sa.Column('environnement_prefere', sa.String(length=255), nullable=True),
    sa.Column('completeness_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_student_profiles_id'), 'student_profiles', ['id'], unique=False)
    op.create_table('formation_domaine',
    sa.Column('formation_id', sa.Integer(), nullable=True),
    sa.Column('domaine_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['domaine_id'], ['domaines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['formation_id'], ['formations.id'], ondelete='CASCADE')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('rag_sources', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('formation_domaine')
    op.drop_index(op.f('ix_student_profiles_id'), table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_formations_intitule'), table_name='formations')
    op.drop_index(op.f('ix_formations_id'), table_name='formations')
    op.drop_index(op.f('ix_formations_diplome'), table_name='formations')
    op.drop_table('formations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_etablissements_ville'), table_name='etablissements')
    op.drop_index(op.f('ix_etablissements_region'), table_name='etablissements')
    op.drop_index(op.f('ix_etablissements_nom'), table_name='etablissements')
    op.drop_index(op.f('ix_etablissements_id'), table_name='etablissements')
    op.drop_table('etablissements')
    op.drop_index(op.f('ix_domaines_nom'), table_name='domaines')
    op.drop_index(op.f('ix_domaines_id'), table_name='domaines')
    op.drop_table('domaines')
    op.drop_index(op.f('ix_data_sources_id'), table_name='data_sources')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
